package com.care.mybatis.dao;

import com.care.mybatis.bean.OpenID;
import com.care.mybatis.bean.OpenIDExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpenIDMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int countByExample(OpenIDExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int deleteByExample(OpenIDExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int insert(OpenID record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int insertSelective(OpenID record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	List<OpenID> selectByExample(OpenIDExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	OpenID selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int updateByExampleSelective(@Param("record") OpenID record, @Param("example") OpenIDExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int updateByExample(@Param("record") OpenID record, @Param("example") OpenIDExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int updateByPrimaryKeySelective(OpenID record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	int updateByPrimaryKey(OpenID record);
}