package com.care.mybatis.dao;

import com.care.mybatis.bean.UserOpenId;
import com.care.mybatis.bean.UserOpenIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOpenIdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int countByExample(UserOpenIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int deleteByExample(UserOpenIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int insert(UserOpenId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int insertSelective(UserOpenId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	List<UserOpenId> selectByExample(UserOpenIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	UserOpenId selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") UserOpenId record, @Param("example") UserOpenIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int updateByExample(@Param("record") UserOpenId record, @Param("example") UserOpenIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int updateByPrimaryKeySelective(UserOpenId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_open_id
	 * @mbggenerated  Mon Apr 28 23:10:09 CST 2014
	 */
	int updateByPrimaryKey(UserOpenId record);
}