package com.care.mybatis.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class OpenIDExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public OpenIDExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNull() {
			addCriterion("openID is null");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNotNull() {
			addCriterion("openID is not null");
			return (Criteria) this;
		}

		public Criteria andOpenidEqualTo(String value) {
			addCriterion("openID =", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotEqualTo(String value) {
			addCriterion("openID <>", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThan(String value) {
			addCriterion("openID >", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThanOrEqualTo(String value) {
			addCriterion("openID >=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThan(String value) {
			addCriterion("openID <", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThanOrEqualTo(String value) {
			addCriterion("openID <=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLike(String value) {
			addCriterion("openID like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotLike(String value) {
			addCriterion("openID not like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidIn(List<String> values) {
			addCriterion("openID in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotIn(List<String> values) {
			addCriterion("openID not in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidBetween(String value1, String value2) {
			addCriterion("openID between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotBetween(String value1, String value2) {
			addCriterion("openID not between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andVendorIsNull() {
			addCriterion("vendor is null");
			return (Criteria) this;
		}

		public Criteria andVendorIsNotNull() {
			addCriterion("vendor is not null");
			return (Criteria) this;
		}

		public Criteria andVendorEqualTo(String value) {
			addCriterion("vendor =", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorNotEqualTo(String value) {
			addCriterion("vendor <>", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorGreaterThan(String value) {
			addCriterion("vendor >", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorGreaterThanOrEqualTo(String value) {
			addCriterion("vendor >=", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorLessThan(String value) {
			addCriterion("vendor <", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorLessThanOrEqualTo(String value) {
			addCriterion("vendor <=", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorLike(String value) {
			addCriterion("vendor like", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorNotLike(String value) {
			addCriterion("vendor not like", value, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorIn(List<String> values) {
			addCriterion("vendor in", values, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorNotIn(List<String> values) {
			addCriterion("vendor not in", values, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorBetween(String value1, String value2) {
			addCriterion("vendor between", value1, value2, "vendor");
			return (Criteria) this;
		}

		public Criteria andVendorNotBetween(String value1, String value2) {
			addCriterion("vendor not between", value1, value2, "vendor");
			return (Criteria) this;
		}

		public Criteria andMetaIsNull() {
			addCriterion("meta is null");
			return (Criteria) this;
		}

		public Criteria andMetaIsNotNull() {
			addCriterion("meta is not null");
			return (Criteria) this;
		}

		public Criteria andMetaEqualTo(String value) {
			addCriterion("meta =", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaNotEqualTo(String value) {
			addCriterion("meta <>", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaGreaterThan(String value) {
			addCriterion("meta >", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaGreaterThanOrEqualTo(String value) {
			addCriterion("meta >=", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaLessThan(String value) {
			addCriterion("meta <", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaLessThanOrEqualTo(String value) {
			addCriterion("meta <=", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaLike(String value) {
			addCriterion("meta like", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaNotLike(String value) {
			addCriterion("meta not like", value, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaIn(List<String> values) {
			addCriterion("meta in", values, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaNotIn(List<String> values) {
			addCriterion("meta not in", values, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaBetween(String value1, String value2) {
			addCriterion("meta between", value1, value2, "meta");
			return (Criteria) this;
		}

		public Criteria andMetaNotBetween(String value1, String value2) {
			addCriterion("meta not between", value1, value2, "meta");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table openid
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table openid
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 10 20:40:14 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}