package com.care.mybatis.bean;

import java.util.Date;

public class OpenID {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column openid.id
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column openid.openID
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column openid.vendor
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	private String vendor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column openid.meta
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	private String meta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column openid.time
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column openid.id
	 * @return  the value of openid.id
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column openid.id
	 * @param id  the value for openid.id
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column openid.openID
	 * @return  the value of openid.openID
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column openid.openID
	 * @param openid  the value for openid.openID
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column openid.vendor
	 * @return  the value of openid.vendor
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public String getVendor() {
		return vendor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column openid.vendor
	 * @param vendor  the value for openid.vendor
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column openid.meta
	 * @return  the value of openid.meta
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public String getMeta() {
		return meta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column openid.meta
	 * @param meta  the value for openid.meta
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setMeta(String meta) {
		this.meta = meta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column openid.time
	 * @return  the value of openid.time
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column openid.time
	 * @param time  the value for openid.time
	 * @mbggenerated  Mon Oct 14 11:08:00 CST 2013
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}