package com.care.mybatis.bean;

public class UICorpDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_corp_desc.id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_corp_desc.intro
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_corp_desc.big_events
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private String bigEvents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_corp_desc.leader_says
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private String leaderSays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_corp_desc.id
     *
     * @return the value of ui_corp_desc.id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_corp_desc.id
     *
     * @param id the value for ui_corp_desc.id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_corp_desc.intro
     *
     * @return the value of ui_corp_desc.intro
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_corp_desc.intro
     *
     * @param intro the value for ui_corp_desc.intro
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_corp_desc.big_events
     *
     * @return the value of ui_corp_desc.big_events
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public String getBigEvents() {
        return bigEvents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_corp_desc.big_events
     *
     * @param bigEvents the value for ui_corp_desc.big_events
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setBigEvents(String bigEvents) {
        this.bigEvents = bigEvents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_corp_desc.leader_says
     *
     * @return the value of ui_corp_desc.leader_says
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public String getLeaderSays() {
        return leaderSays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_corp_desc.leader_says
     *
     * @param leaderSays the value for ui_corp_desc.leader_says
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setLeaderSays(String leaderSays) {
        this.leaderSays = leaderSays;
    }
}