package com.care.mybatis.bean;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.profile_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private Integer profileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.nick
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.open_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private Integer openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.integ_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private Integer integId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.time
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role_id
	 * @return  the value of user.role_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role_id
	 * @param roleId  the value for user.role_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.profile_id
	 * @return  the value of user.profile_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public Integer getProfileId() {
		return profileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.profile_id
	 * @param profileId  the value for user.profile_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.nick
	 * @return  the value of user.nick
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.nick
	 * @param nick  the value for user.nick
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setNick(String nick) {
		this.nick = nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.open_id
	 * @return  the value of user.open_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public Integer getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.open_id
	 * @param openId  the value for user.open_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setOpenId(Integer openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.integ_id
	 * @return  the value of user.integ_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public Integer getIntegId() {
		return integId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.integ_id
	 * @param integId  the value for user.integ_id
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setIntegId(Integer integId) {
		this.integId = integId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.time
	 * @return  the value of user.time
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.time
	 * @param time  the value for user.time
	 * @mbggenerated  Mon Oct 14 11:07:59 CST 2013
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}