package com.care.mybatis.bean;

import java.util.Date;

public class UserOpenId {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open_id.id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open_id.open_id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open_id.vendor
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open_id.meta
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private String meta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open_id.date
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open_id.id
     *
     * @return the value of user_open_id.id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open_id.id
     *
     * @param id the value for user_open_id.id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open_id.open_id
     *
     * @return the value of user_open_id.open_id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open_id.open_id
     *
     * @param openId the value for user_open_id.open_id
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open_id.vendor
     *
     * @return the value of user_open_id.vendor
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open_id.vendor
     *
     * @param vendor the value for user_open_id.vendor
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open_id.meta
     *
     * @return the value of user_open_id.meta
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public String getMeta() {
        return meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open_id.meta
     *
     * @param meta the value for user_open_id.meta
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setMeta(String meta) {
        this.meta = meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open_id.date
     *
     * @return the value of user_open_id.date
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open_id.date
     *
     * @param date the value for user_open_id.date
     *
     * @mbggenerated Sun Apr 20 14:09:07 CST 2014
     */
    public void setDate(Date date) {
        this.date = date;
    }
}